@extends('layouts.app')
@section('title','Message Thread')
@section('page-title','Messages')
@push('styles')
<style>
.pg{display:grid;grid-template-columns:240px 1fr;gap:16px}.card{background:white;border:1px solid var(--border);border-radius:12px;overflow:hidden;margin-bottom:14px}.ch{padding:13px 18px;border-bottom:1px solid var(--border);background:#F8FAFC;font-size:13px;font-weight:700;color:var(--midnight)}.msg{padding:16px 18px;border-bottom:1px solid var(--border)}.msg.mine{background:#EFF6FF}.msg-header{display:flex;align-items:center;gap:8px;margin-bottom:6px}.msg-av{width:28px;height:28px;border-radius:50%;background:var(--indigo);color:white;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center}.msg-sender{font-size:12px;font-weight:700}.msg-time{font-size:11px;color:var(--slate-light);margin-left:auto}.msg-body{font-size:13px;color:var(--slate);line-height:1.6;padding-left:36px}.reply-box{padding:16px 18px;border-top:1px solid var(--border);background:#F8FAFC}.fc{padding:10px 13px;font-size:13px;font-family:inherit;border:1px solid var(--border);border-radius:9px;background:white;width:100%;resize:vertical}.btn{display:inline-flex;align-items:center;gap:6px;padding:9px 18px;font-size:13px;font-weight:600;border-radius:8px;border:none;cursor:pointer}.btn-p{background:var(--indigo);color:white}.btn-ghost{background:white;border:1px solid var(--border);color:var(--midnight)}.info-row{display:flex;justify-content:space-between;padding:8px 14px;border-bottom:1px solid var(--border);font-size:12.5px}.ik{color:var(--slate)}.iv{font-weight:600;text-align:right}.back{font-size:13px;color:var(--indigo);text-decoration:none;display:inline-flex;margin-bottom:16px}.note{background:#FFF7ED;border:1px solid #FED7AA;border-radius:8px;padding:12px 16px;font-size:13px;color:#9A3412;margin:0 18px 16px;text-align:center}.alert-s{background:#ECFDF5;border:1px solid #A7F3D0;border-radius:8px;padding:12px 16px;font-size:13px;color:var(--emerald);margin-bottom:14px}@media(max-width:768px){.pg{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
@if(session('success'))<div class="alert-s">{{ session('success') }}</div>@endif
<a href="{{ route('messages.inbox') }}" class="back">← Inbox</a>
@php $type=$thread->conversation_type ?? 'student'; $target=match($type){'all_staff'=>'All Staff','all_parents'=>'All Parents','admin'=>'School Administration','staff'=>'Staff: '.(optional($thread->recipient)->name ?? optional($thread->initiator)->name ?? 'Staff'),'parent'=>'Parent: '.(optional($thread->recipient)->name ?? optional($thread->initiator)->name ?? 'Parent'),default=>optional($thread->student)->full_name ?? 'Student-linked conversation'}; @endphp
<div class="pg"><div><div class="card"><div class="ch">Thread Info</div><div class="info-row"><span class="ik">Conversation</span><span class="iv">{{ $target }}</span></div>@if($thread->student_id)<div class="info-row"><span class="ik">Adm No</span><span class="iv">{{ optional($thread->student)->admission_number }}</span></div>@endif<div class="info-row"><span class="ik">Started by</span><span class="iv">{{ optional($thread->initiator)->name }}</span></div><div class="info-row"><span class="ik">Status</span><span class="iv">{{ ucfirst($thread->status) }}</span></div>@if($thread->audience)<div class="info-row"><span class="ik">Mode</span><span class="iv">Broadcast</span></div>@endif</div></div><div><div class="card"><div class="ch">{{ $thread->subject }}</div>@foreach($thread->replies as $reply)@php $isMe=(int)$reply->sender_id===(int)auth()->id(); @endphp<div class="msg {{ $isMe?'mine':'' }}"><div class="msg-header"><div class="msg-av">{{ strtoupper(substr(optional($reply->sender)->name ?? 'U',0,1)) }}</div><span class="msg-sender">{{ $isMe?'You':optional($reply->sender)->name }}</span><span class="msg-time">{{ $reply->created_at->diffForHumans() }}</span></div><div class="msg-body">{{ $reply->body }}</div></div>@endforeach@if($thread->status==='open')@if($thread->audience && (int)$thread->initiated_by !== (int)auth()->id())<div class="note">Replies to this broadcast are sent privately to school administration and are not visible to other recipients.</div>@endif<div class="reply-box"><form method="POST" action="{{ route('messages.reply',$thread) }}">@csrf<textarea name="body" class="fc" rows="3" maxlength="10000" placeholder="Type your reply..." required></textarea><div style="margin-top:10px"><button type="submit" class="btn btn-p">Send Reply</button></div></form></div>@endif</div></div></div>
@endsection
