<style>
.repository-reader{padding-bottom:28px}
.reader-hero{position:relative;margin-bottom:14px;padding:26px 28px 104px;overflow:hidden;border:1px solid #d9e5f2;border-radius:16px;background:linear-gradient(135deg,#fff 0%,#f7fbff 58%,#eef6ff 100%);box-shadow:0 12px 32px rgba(13,49,91,.07)}
.reader-hero:before{content:'';position:absolute;right:-110px;top:-135px;width:330px;height:330px;border:60px solid rgba(21,87,166,.045);border-radius:50%}
.reader-hero-copy{position:relative;z-index:1;max-width:650px}.reader-kicker{display:inline-flex;align-items:center;gap:7px;color:#1f67b3;font-size:9px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.reader-kicker i{width:7px;height:7px;border-radius:50%;background:#d79a21;box-shadow:0 0 0 4px rgba(215,154,33,.13)}
.reader-hero h1{margin:9px 0 7px;color:#071e45;font-size:30px;line-height:1.15;font-weight:850;letter-spacing:-.035em}.reader-hero p{max-width:590px;margin:0;color:#61748c;font-size:12px;line-height:1.65}
.reader-hero-mark{position:absolute;z-index:1;right:34px;top:22px;width:78px;height:78px;display:grid;place-items:center;border:1px solid rgba(21,87,166,.12);border-radius:20px;color:#1557a6;background:rgba(255,255,255,.75);box-shadow:0 10px 25px rgba(15,58,106,.08);backdrop-filter:blur(8px)}.reader-hero-mark svg{width:46px;height:46px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.reader-metrics{position:absolute;z-index:2;left:28px;right:28px;bottom:18px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.reader-metric{min-height:66px;padding:11px 13px;display:flex;align-items:center;gap:10px;border:1px solid rgba(208,222,237,.9);border-radius:10px;background:rgba(255,255,255,.9);box-shadow:0 5px 16px rgba(16,51,91,.045);backdrop-filter:blur(7px)}.reader-metric>span{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border-radius:9px;color:#2069b5;background:#edf5fe}.reader-metric svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.reader-metric strong{display:block;color:#071e45;font-size:16px;line-height:1;font-weight:850}.reader-metric small{display:block;margin-top:4px;color:#78899d;font-size:8.5px;font-weight:650}
.reader-toolbar{padding:10px;display:flex;align-items:center;gap:8px;box-shadow:0 8px 24px rgba(16,51,91,.04)}.reader-toolbar .repo-search{height:40px}.reader-subject-filter{width:230px}.reader-subject-filter select{height:40px}.reader-toolbar .repo-button{min-height:40px}
.repository-reader .repo-section-heading{margin-top:20px}.repository-reader .repo-section-heading h2{font-size:15px}.repository-reader .repo-section-heading p{font-size:9.5px}
.repository-reader .repo-class-stat{min-height:98px;border-radius:12px}.repository-reader .repo-class-stat.active{border-color:#1557a6;background:linear-gradient(145deg,#fff,#f3f8fe)}.reader-class-foot{grid-column:1/-1;padding-top:8px;display:flex;align-items:center;gap:4px;border-top:1px solid #e9f0f7;color:#6e8197;font-size:8.5px}.reader-class-foot b{color:#158557}.reader-class-foot svg{width:13px;height:13px;margin-left:auto;fill:none;stroke:#6d85a0;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.reader-hierarchy .repo-class-panel{border-radius:13px;box-shadow:0 10px 28px rgba(15,52,94,.055)}.reader-hierarchy .repo-hierarchy-head{background:linear-gradient(90deg,#fff,#fafcff)}.reader-hierarchy .repo-term-tabs{padding:10px 13px}.reader-hierarchy .repo-term-panel{padding:15px}
.reader-subject>summary{grid-template-columns:38px minmax(0,1fr) auto 18px!important;min-height:66px;padding:11px 13px!important}.reader-ready{display:inline-flex;align-items:center;gap:5px;padding:5px 8px;border-radius:999px;color:#147248;background:#eaf9f1;font-size:8px;font-weight:750}.reader-ready i{width:5px;height:5px;border-radius:50%;background:#16a064}
.reader-resource{grid-template-columns:42px minmax(0,1fr) auto!important;min-height:70px;padding:12px 14px!important}.reader-resource .repo-file-mark{width:42px;height:46px;border:1px solid #dceafb}.reader-resource .repo-resource-copy h3{font-size:11.5px}.reader-resource .repo-resource-actions .repo-button{min-height:34px;padding:0 11px;font-size:9px}
.reader-empty{min-height:330px;padding:35px;display:flex;align-items:center;justify-content:center;flex-direction:column;text-align:center}.reader-empty>span{width:72px;height:72px;display:grid;place-items:center;border-radius:20px;color:#2774c8;background:#edf5fe}.reader-empty>span svg{width:38px;height:38px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.reader-empty h2{margin:15px 0 5px;color:#071e45;font-size:16px}.reader-empty p{margin:0 0 14px;color:#78899d;font-size:10.5px}
.reader-document-head{margin-bottom:16px;padding:22px 24px;display:flex;align-items:center;justify-content:space-between;gap:22px;border:1px solid #d9e5f2;border-radius:14px;background:linear-gradient(135deg,#fff,#f5f9fe);box-shadow:0 10px 28px rgba(13,49,91,.055)}.reader-document-title{min-width:0}.reader-document-title h1{margin:8px 0 10px;color:#071e45;font-size:25px;line-height:1.2;letter-spacing:-.025em}.reader-document-tags{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.reader-document-tags span{padding:5px 8px;border:1px solid #d9e6f3;border-radius:999px;color:#4a6685;background:#fff;font-size:8.5px;font-weight:700}.reader-document-actions{display:flex;align-items:center;gap:8px;flex-shrink:0}
.reader-document-layout{display:grid;grid-template-columns:minmax(0,1fr) 260px;align-items:start;gap:15px}.reader-note{overflow:hidden;border:1px solid #dce5ef;border-radius:14px;background:#fff;box-shadow:0 10px 30px rgba(13,49,91,.055)}.reader-note-cover{min-height:118px;padding:22px 24px;display:flex;align-items:center;gap:16px;color:#fff;background:linear-gradient(125deg,#071e45,#123d78)}.reader-note-cover>span{width:55px;height:55px;flex:0 0 55px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.23);border-radius:15px;color:#f5c65d;background:rgba(255,255,255,.08);font-size:15px;font-weight:850}.reader-note-cover small{color:#b8c8dd;font-size:8.5px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.reader-note-cover h2{margin:5px 0 3px;color:#fff;font-size:19px;line-height:1.25}.reader-note-cover p{margin:0;color:#d9e4f0;font-size:10px}
.reader-note-section{padding:22px 25px;border-bottom:1px solid #e8eef5;scroll-margin-top:75px}.reader-note-section:last-child{border-bottom:0}.reader-note-section>header{margin-bottom:15px;display:flex;align-items:center;gap:11px}.reader-note-section>header>span{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border-radius:9px;color:#1f67b2;background:#eaf3fd;font-size:9px;font-weight:850}.reader-note-section>header small{display:block;color:#8997a8;font-size:7.5px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}.reader-note-section>header h3{margin:3px 0 0;color:#132f50;font-size:14px;line-height:1.35}.reader-note-content{color:#334b68;font-size:11.5px;line-height:1.85;white-space:normal}.reader-note-empty{padding:35px;color:#71839a;text-align:center;font-size:11px}
.reader-document-aside{position:sticky;top:74px;display:grid;gap:11px}.reader-info-card,.reader-toc{padding:16px}.reader-info-kicker{display:block;margin-bottom:11px;color:#2469b0;font-size:8px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.reader-info-card dl{margin:0 0 14px}.reader-info-card dl div{padding:8px 0;display:grid;grid-template-columns:70px minmax(0,1fr);gap:8px;border-bottom:1px solid #edf2f7}.reader-info-card dt{color:#8998aa;font-size:8.5px}.reader-info-card dd{min-width:0;margin:0;overflow-wrap:anywhere;color:#294461;font-size:8.8px;font-weight:700;text-align:right}.reader-toc{max-height:340px;overflow:auto}.reader-toc a{padding:8px 0;display:flex;align-items:flex-start;gap:8px;border-bottom:1px solid #edf2f7;color:#4c6683;font-size:8.8px;line-height:1.4;text-decoration:none}.reader-toc a:last-child{border-bottom:0}.reader-toc a:hover{color:#1557a6}.reader-toc b{color:#2774c8;font-size:8px}.reader-toc span{min-width:0}
@media(max-width:950px){.reader-hero-mark{display:none}.reader-document-layout{grid-template-columns:minmax(0,1fr) 230px}.reader-document-head{align-items:flex-start}.reader-document-actions{flex-direction:column;align-items:stretch}}
@media(max-width:760px){.reader-hero{padding:22px 20px 178px}.reader-metrics{left:20px;right:20px;grid-template-columns:repeat(2,minmax(0,1fr))}.reader-toolbar{align-items:stretch;flex-wrap:wrap}.reader-toolbar .repo-search{flex-basis:100%}.reader-subject-filter{min-width:0;flex:1}.reader-document-head{padding:18px;flex-direction:column}.reader-document-actions{width:100%;display:grid;grid-template-columns:1fr 1fr}.reader-document-layout{grid-template-columns:1fr}.reader-document-aside{position:static;grid-template-columns:1fr 1fr}.reader-note-section{padding:19px}.reader-resource{grid-template-columns:38px minmax(0,1fr)!important}.reader-resource .repo-resource-actions{grid-column:2;display:grid;grid-template-columns:1fr 1fr}.reader-resource .repo-button{width:100%}}
@media(max-width:520px){.reader-hero{padding:20px 17px 174px}.reader-hero h1{font-size:24px}.reader-hero p{font-size:10.5px}.reader-metrics{left:12px;right:12px;bottom:12px;gap:6px}.reader-metric{min-height:61px;padding:9px}.reader-metric>span{width:30px;height:30px;flex-basis:30px}.reader-metric strong{font-size:14px}.reader-toolbar .repo-button{flex:1}.reader-subject-filter{flex-basis:100%;width:100%}.reader-subject>summary{grid-template-columns:34px minmax(0,1fr) 16px!important}.reader-ready{grid-column:2;justify-self:start}.reader-document-actions{grid-template-columns:1fr}.reader-document-title h1{font-size:21px}.reader-document-aside{grid-template-columns:1fr}.reader-note-cover{padding:18px}.reader-note-cover>span{width:48px;height:48px;flex-basis:48px}.reader-note-cover h2{font-size:16px}.reader-note-section{padding:16px}.reader-note-content{font-size:11px;line-height:1.75}}
</style>
