<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Staff Clock-In QR — {{ optional(auth()->user()->tenant)->name }}</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{font-family:'Inter',system-ui,sans-serif;background:linear-gradient(135deg,#0F172A 0%,#1E3A5F 60%,#0F172A 100%);min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;color:white;padding:20px;gap:20px}.admin-bar{display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:10px 16px;flex-wrap:wrap}.admin-bar span{font-size:12px;color:rgba(255,255,255,.5);margin-right:6px}.btn{padding:7px 14px;font-size:12px;font-weight:600;font-family:inherit;border-radius:7px;border:none;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;gap:5px}.btn-white{background:white;color:#1E293B}.btn-ghost{background:rgba(255,255,255,.1);color:white;border:1px solid rgba(255,255,255,.2)}.btn-danger{background:rgba(220,38,38,.2);color:#FCA5A5;border:1px solid rgba(220,38,38,.3)}.live-clock{font-size:56px;font-weight:900;letter-spacing:-.03em;font-variant-numeric:tabular-nums}.live-date{font-size:14px;color:rgba(255,255,255,.6);margin-top:4px}.qr-card{background:white;border-radius:20px;padding:28px;display:flex;flex-direction:column;align-items:center;gap:14px;box-shadow:0 30px 80px rgba(0,0,0,.4);max-width:380px;width:100%}.qr-school{font-size:12px;font-weight:800;color:#94A3B8;text-transform:uppercase;letter-spacing:.08em}.qr-title{font-size:20px;font-weight:900;color:#1E293B;text-align:center}.qr-img-wrap{border:3px solid #E2E8F0;border-radius:14px;padding:10px;background:white}.qr-img{width:260px;height:260px;display:block}.qr-error{width:260px;min-height:200px;display:flex;align-items:center;justify-content:center;text-align:center;padding:22px;color:#991B1B;background:#FEF2F2;border-radius:10px;font-size:13px;line-height:1.55}.rules{display:flex;gap:8px;flex-wrap:wrap;justify-content:center}.rule-pill{padding:5px 12px;border-radius:20px;font-size:11px;font-weight:700}.r-early{background:#E0F2FE;color:#0284C7}.r-present{background:#DCFCE7;color:#15803D}.r-late{background:#FEF9C3;color:#A16207}.qr-instruction{font-size:12px;color:#64748B;text-align:center;line-height:1.6}.static-badge{display:inline-flex;align-items:center;gap:5px;background:#ECFDF5;color:#059669;border:1px solid #A7F3D0;border-radius:20px;padding:4px 12px;font-size:11px;font-weight:700}.fullscreen-hint,.no-phone{font-size:11px;color:rgba(255,255,255,.4);text-align:center}.no-phone{font-size:12px;max-width:360px;line-height:1.6}@media print{.admin-bar,.fullscreen-hint,.no-phone,.live-clock,.live-date{display:none}body{background:white;color:#1E293B}.qr-card{box-shadow:none;border:2px solid #E2E8F0}}
</style>
</head>
<body>
<div class="admin-bar"><span>Admin controls:</span><a href="{{ route('staff-attendance.index') }}" class="btn btn-ghost">← Dashboard</a><button onclick="document.documentElement.requestFullscreen()" class="btn btn-white">⛶ Fullscreen</button><button onclick="window.print()" class="btn btn-ghost">🖨 Print QR</button><form method="POST" action="{{ route('staff-attendance.reset-qr') }}" style="display:inline" onsubmit="return confirm('Reset the school attendance QR? Previously printed copies will stop working.')">@csrf<button type="submit" class="btn btn-danger">↻ Reset QR</button></form></div>
<div style="text-align:center"><div class="live-clock" id="clock">--:--:--</div><div class="live-date">{{ \Carbon\Carbon::now()->format('l, d F Y') }}</div></div>
<div class="qr-card"><div class="qr-school">{{ optional(auth()->user()->tenant)->name ?? 'School' }}</div><div class="qr-title">School Attendance QR</div><div class="qr-img-wrap">@if($qrBase64)<img src="{{ $qrBase64 }}" class="qr-img" alt="School attendance QR code">@else<div class="qr-error">The local QR renderer could not generate this code. Refresh the page. If the problem persists, check the Simple QrCode installation on the server.</div>@endif</div><div class="static-badge">✓ School QR active until reset</div><div class="rules"><span class="rule-pill r-early">Early — before {{ \Carbon\Carbon::parse($settings->resumption_time)->format('H:i') }}</span><span class="rule-pill r-present">Present — within {{ $settings->grace_minutes }}min grace</span><span class="rule-pill r-late">Late — after {{ \Carbon\Carbon::parse($settings->resumption_time)->addMinutes($settings->grace_minutes)->format('H:i') }}</span></div><div class="qr-instruction">Open <strong>EduCore</strong> and scan this school QR to clock in. The token is validated by the server for this school.</div></div>
<div class="no-phone">No phone? An authorized colleague or administrator can use the approved proxy attendance flow.</div><div class="fullscreen-hint">Press F11 for fullscreen · This QR remains valid until an administrator resets it</div>
<script>function updateClock(){const n=new Date();document.getElementById('clock').textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0')+':'+String(n.getSeconds()).padStart(2,'0')}updateClock();setInterval(updateClock,1000)</script>
</body>
</html>
