@extends('layouts.app')
@section('title', 'Invoice Generation History')
@section('page-title', 'Invoice Generation History')

@push('styles')
<style>
    .history-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}
    .history-back{display:inline-flex;align-items:center;gap:6px;color:var(--brand-navy);font-size:13px;font-weight:700;text-decoration:none}
    .history-back:hover{color:var(--brand-gold-dark)}
    .history-card{background:#fff;border:1px solid var(--border);border-radius:14px;box-shadow:0 8px 24px rgba(15,23,42,.05);overflow:hidden}
    .history-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 20px;border-bottom:1px solid var(--border);background:var(--brand-navy-soft)}
    .history-title{font-size:14px;font-weight:800;color:var(--brand-navy)}
    .history-count{display:inline-flex;align-items:center;min-height:30px;padding:4px 10px;border-radius:999px;background:var(--brand-gold-light);color:var(--brand-navy);font-size:11px;font-weight:800}
    .history-table-wrap{overflow-x:auto}
    .history-table{width:100%;min-width:1080px;border-collapse:collapse}
    .history-table th{padding:10px 12px;text-align:left;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:var(--slate-light);border-bottom:1px solid var(--border);background:#F8FAFC;white-space:nowrap}
    .history-table td{padding:12px;border-bottom:1px solid var(--border);font-size:13px;color:var(--midnight);vertical-align:top}
    .history-table tbody tr:hover td{background:#FAFCFF}
    .history-table tbody tr:last-child td{border-bottom:0}
    .history-id{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--slate-light)}
    .history-sub{display:block;margin-top:2px;font-size:11px;font-weight:400;color:var(--slate-light)}
    .history-money{font-weight:800;color:var(--brand-navy);white-space:nowrap}
    .history-positive{color:var(--emerald);font-weight:800}.history-warning{color:var(--amber);font-weight:700}
    .status-badge{display:inline-flex;align-items:center;min-height:28px;padding:3px 9px;border-radius:999px;font-size:11px;font-weight:800}
    .status-done{background:#ECFDF5;color:#047857}.status-partial{background:#FFFBEB;color:#B45309}.status-void{background:#FEF2F2;color:#B91C1C}
    .btn-danger-soft{display:inline-flex;align-items:center;justify-content:center;min-height:36px;padding:7px 12px;border:1px solid #FECACA;border-radius:8px;background:#FEF2F2;color:#B91C1C;font:inherit;font-size:12px;font-weight:800;cursor:pointer}
    .btn-danger-soft:hover{background:#FEE2E2}
    .history-note{margin-top:6px;max-width:220px;font-size:11px;line-height:1.45;color:var(--slate-light)}
    .history-empty{padding:52px 20px;text-align:center;color:var(--slate-light)}
    .history-empty strong{display:block;margin-bottom:6px;color:var(--slate);font-size:15px}
    .history-pagination{padding:14px 18px;border-top:1px solid var(--border)}
</style>
@endpush

@section('content')
<div class="history-toolbar">
    <a href="{{ route('fees.generate.index') }}" class="history-back" aria-label="Back to invoice generator">← Back to Generator</a>
</div>

<div class="history-card">
    <div class="history-head">
        <div>
            <div class="history-title">All Generation Batches</div>
            <div style="margin-top:3px;font-size:12px;color:var(--slate)">Audit trail of generated invoice batches and their outcomes.</div>
        </div>
        <span class="history-count">{{ $batches->total() }} batches</span>
    </div>

    @if($batches->count())
    <div class="history-table-wrap">
        <table class="history-table">
            <thead>
                <tr>
                    <th scope="col">Batch</th><th scope="col">Term</th><th scope="col">Scope</th><th scope="col">Students</th><th scope="col">Generated</th><th scope="col">Skipped</th><th scope="col">Total Value</th><th scope="col">Generated By</th><th scope="col">When</th><th scope="col">Status</th><th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach($batches as $batch)
                <tr>
                    <td><span class="history-id">#{{ $batch->id }}</span></td>
                    <td>
                        <strong>{{ optional($batch->term)->name }}</strong>
                        <span class="history-sub">{{ optional(optional($batch->term)->session)->name }}</span>
                    </td>
                    <td>
                        @if($batch->scope === 'class_level')
                            {{ optional($batch->classLevel)->name ?? 'All Levels' }}
                        @elseif($batch->scope === 'class_arm')
                            {{ optional($batch->classArm)->name ?? '—' }}
                        @else
                            All Students
                        @endif
                    </td>
                    <td>{{ $batch->total_students }}</td>
                    <td class="history-positive">{{ $batch->generated_count }}</td>
                    <td class="history-warning">{{ $batch->skipped_count }}</td>
                    <td class="history-money">₦{{ number_format($batch->total_value) }}</td>
                    <td>{{ optional($batch->generatedBy)->name ?? '—' }}</td>
                    <td style="white-space:nowrap">{{ $batch->created_at->format('d M Y H:i') }}</td>
                    <td>
                        @if($batch->status === 'completed')
                            <span class="status-badge status-done">Completed</span>
                        @elseif($batch->status === 'partial')
                            <span class="status-badge status-partial">Partial</span>
                        @else
                            <span class="status-badge status-void">Voided</span>
                        @endif
                    </td>
                    <td>
                        @if($batch->status === 'completed')
                            <form method="POST" action="{{ route('fees.generate.batch.void', $batch) }}" onsubmit="return confirm('Void batch #{{ $batch->id }}? All unpaid invoices in it will be permanently deleted.')">
                                @csrf @method('DELETE')
                                <button type="submit" class="btn-danger-soft">Void batch</button>
                            </form>
                        @endif
                        @if($batch->notes)
                            <div class="history-note">{{ $batch->notes }}</div>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    @else
        <div class="history-empty">
            <strong>No generation batches yet</strong>
            <span>Generated invoice batches will appear here for review and audit.</span>
        </div>
    @endif

    @if($batches->hasPages())
        <div class="history-pagination">{{ $batches->links() }}</div>
    @endif
</div>
@endsection
