name: educore_staff
description: EduCore Staff — attendance, classes, and announcements on the go.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  mobile_scanner: ^5.2.3
  geolocator: ^13.0.1
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  share_plus: ^10.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/educore-icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/educore-icon-fg.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/educore-icon.svg
