@extends($platform ? 'layouts.super' : 'layouts.app')
@section('title', 'Curriculum Sources')
@section('content')
<div class="page-content"><div style="display:flex;justify-content:space-between;gap:20px;align-items:flex-start;flex-wrap:wrap;margin-bottom:22px"><div><div style="font-size:12px;font-weight:800;color:#2563eb;text-transform:uppercase;letter-spacing:.12em">Curriculum Intelligence</div><h1 style="font-size:25px;margin:5px 0;color:#0f172a">{{ $platform ? 'Official curriculum library' : 'School curriculum sources' }}</h1><p style="color:#64748b;max-width:720px">Upload traceable teaching sources. Nothing is used for AI grounding until an authorised reviewer activates it.</p></div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div style="display:grid;grid-template-columns:minmax(0,1.5fr) minmax(320px,.8fr);gap:20px;align-items:start" class="source-grid"><div style="background:#fff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden"><div style="padding:18px 20px;border-bottom:1px solid #e2e8f0"><h3>Source register</h3></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr style="background:#f8fafc"><th>Source</th><th>Authority</th><th>Version</th><th>Evidence</th><th>Status</th><th></th></tr></thead><tbody>@forelse($sources as $source)<tr><td><b>{{ $source->title }}</b><small style="display:block;color:#64748b">{{ $source->source_type }}</small></td><td>{{ $source->authority }}</td><td>{{ $source->version }}</td><td>{{ $source->fragments_count }} fragments</td><td><span style="padding:4px 9px;border-radius:999px;background:{{ $source->is_active?'#dcfce7':'#fef3c7' }};color:{{ $source->is_active?'#166534':'#92400e' }}">{{ $source->is_active?'Active':'Pending review' }}</span></td><td>@unless($source->is_active)<form method="POST" action="{{ $platform ? route('super.curriculum-sources.activate',$source) : route('curriculum-sources.activate',$source) }}">@csrf<button class="btn btn-secondary">Review & activate</button></form>@endunless</td></tr>@empty<tr><td colspan="6" style="padding:32px;text-align:center;color:#64748b">No curriculum sources uploaded yet.</td></tr>@endforelse</tbody></table></div><div style="padding:15px">{{ $sources->links() }}</div></div>
<aside style="background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:20px"><h3>Register curriculum or textbook source</h3><p style="font-size:13px;color:#64748b;margin:6px 0 10px">Supported: TXT, CSV and DOCX up to 15 MB.</p><div style="font-size:12px;line-height:1.55;padding:10px 12px;background:#eff6ff;color:#1e40af;border-radius:9px">For a textbook, enter the NERDC/FME approval-list reference and upload only material your institution is licensed or authorised to use.</div><form method="POST" enctype="multipart/form-data" action="{{ $platform ? route('super.curriculum-sources.store') : route('curriculum-sources.store') }}">@csrf
@foreach([['title','Source title','text'],['version','Version / year','text'],['topic','Topic represented','text'],['subtopic','Subtopic (optional)','text']] as $field)<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">{{ $field[1] }}</label><input name="{{ $field[0] }}" type="{{ $field[2] }}" value="{{ old($field[0]) }}" {{ $field[0]==='subtopic'?'':'required' }} style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px">@endforeach
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Authority</label><select name="authority" required style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px">@foreach($platform?['NERDC','WAEC','NECO','JAMB','TEXTBOOK','OTHER']:['SCHOOL','TEXTBOOK','OTHER'] as $a)<option>{{ $a }}</option>@endforeach</select>
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Source type</label><select name="source_type" required style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px"><option value="curriculum_document">Curriculum document</option><option value="teacher_guide">Teacher's guide</option><option value="assessment_syllabus">Assessment syllabus</option><option value="approved_textbook">Approved textbook</option><option value="school_scheme">School scheme of work</option></select>
@foreach([['publisher','Publisher (textbook)'],['authors','Author(s)'],['isbn','ISBN'],['approval_reference','NERDC/FME approval reference']] as $field)<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">{{ $field[1] }}</label><input name="{{ $field[0] }}" value="{{ old($field[0]) }}" style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px">@endforeach
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Usage rights</label><select name="rights_status" required style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px"><option value="institution_authorised">Institution-authorised copy</option><option value="licensed">Licensed digital content</option>@if($platform)<option value="public_official">Public official material</option>@endif</select>
@if($platform)<label style="display:flex;gap:8px;align-items:flex-start;font-size:12px;margin-top:12px"><input type="checkbox" name="is_official" value="1"> <span>Mark as officially verified only after checking the issuing authority or current approval catalogue.</span></label>@endif
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Subject</label><select name="subject_id" style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px"><option value="">All subjects</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select>
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Class</label><select name="class_level_id" style="width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:9px"><option value="">Multiple classes</option>@foreach($classLevels as $level)<option value="{{ $level->id }}">{{ $level->name }}</option>@endforeach</select>
<label style="display:block;font-size:12px;font-weight:700;margin:12px 0 5px">Document</label><input name="source_file" type="file" accept=".txt,.csv,.docx" required style="width:100%;padding:12px;border:1px dashed #94a3b8;border-radius:9px"><button class="btn btn-primary" style="width:100%;margin-top:16px">Secure upload</button></form></aside></div></div>
<style>table th,table td{padding:13px 15px;text-align:left;border-bottom:1px solid #e2e8f0;font-size:13px}@media(max-width:900px){.source-grid{grid-template-columns:1fr!important}}</style>
@endsection
