<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Cumulative Broadsheet</title>
<style>
@page{size:A4 landscape;margin:9mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:7px;margin:0}.hdr{display:table;width:100%;padding-bottom:6px;margin-bottom:7px;border-bottom:2px solid #D79A21}.logo{display:table-cell;width:52px;vertical-align:middle}.logo img{max-width:43px;max-height:43px}.brand{display:table-cell;vertical-align:middle}.school{font-size:14px;font-weight:800;color:#071E45;text-transform:uppercase}.contact{font-size:6.5px;color:#667085;margin-top:2px}.doc{display:table-cell;text-align:right;vertical-align:middle}.doc strong{display:block;font-size:12px;color:#071E45}.doc span{font-size:7px;color:#667085}.ctx{padding:6px 8px;background:#F8FAFC;border:1px solid #DDE3EC;margin-bottom:7px}.ctx strong{font-size:9px;color:#071E45}.ctx span{font-size:7px;color:#667085}.tbl{width:100%;border-collapse:collapse;table-layout:fixed}.tbl th{padding:4px 3px;background:#071E45;color:#fff;border:1px solid #334E75;text-align:center;font-size:6.3px}.tbl th:first-child{width:15%;text-align:left}.tbl td{padding:4px 3px;border:1px solid #DDE3EC;text-align:center;font-size:6.7px}.tbl td:first-child{text-align:left}.name{font-weight:700;color:#071E45}.adm{font-size:5.6px;color:#667085}.sum{font-weight:700;background:#F8FAFC}.stats td{background:#EFF6FF;font-size:5.8px;line-height:1.4}.key{margin-top:6px;font-size:5.8px;color:#667085}.footer{margin-top:7px;padding-top:5px;border-top:1px solid #DDE3EC;font-size:6px;color:#94A3B8;text-align:right}
</style>
</head>
<body>
<div class="hdr">
<div class="logo">@if($logoAbsPath)<img src="{{ $logoAbsPath }}" alt="Logo">@endif</div>
<div class="brand"><div class="school">{{ $tenant?->name }}</div><div class="contact">{{ $tenant?->address }} @if($tenant?->phone) · {{ $tenant->phone }} @endif @if($tenant?->email) · {{ $tenant->email }} @endif</div></div>
<div class="doc"><strong>CUMULATIVE CLASS BROADSHEET</strong><span>{{ $session->name }}</span></div>
</div>
<div class="ctx"><strong>{{ $classArm->classLevel?->name }} {{ $classArm->name }}</strong><span> · {{ $matrix->count() }} learners · {{ $subjects->count() }} subjects · {{ $terms->count() }} terms</span></div>
<table class="tbl">
<thead><tr>
<th>Learner</th>
@foreach($terms as $index=>$term)<th>{{ $index+1 }}T Avg</th>@endforeach
@foreach($subjects as $subject)<th>{{ $subject->code ?: \Illuminate\Support\Str::limit($subject->name,6,'') }}</th>@endforeach
<th>Total</th><th>Avg</th><th>Pos</th>
</tr></thead>
<tbody>
@foreach($matrix as $row)
<tr>
<td><div class="name">{{ $row['student']->full_name }}</div><div class="adm">{{ $row['student']->admission_number }}</div></td>
@foreach($terms as $term)@php($ta=$row['term_averages'][(int)$term->id] ?? null)<td>{{ $ta===null?'—':number_format($ta,1) }}</td>@endforeach
@foreach($subjects as $subject)@php($sd=$row['subjects'][(int)$subject->id] ?? null)<td>{{ ($sd['average'] ?? null)===null?'—':number_format($sd['average'],1) }}</td>@endforeach
<td class="sum">{{ number_format($row['total'],1) }}</td><td class="sum">{{ number_format($row['average'],1) }}</td><td class="sum">{{ $row['position'] }}</td>
</tr>
@endforeach
<tr class="stats"><td><strong>Class Stats</strong></td>@foreach($terms as $term)<td>—</td>@endforeach @foreach($subjects as $subject)@php($st=$subjectStats->get((int)$subject->id,[]))<td>H {{ $st['highest'] ?? '—' }}<br>L {{ $st['lowest'] ?? '—' }}<br>A {{ $st['avg'] ?? '—' }}</td>@endforeach<td colspan="3"></td></tr>
</tbody>
</table>
<div class="key"><strong>Subject Key:</strong> @foreach($subjects as $subject){{ $subject->code ?: \Illuminate\Support\Str::limit($subject->name,6,'') }} = {{ $subject->name }}@if(!$loop->last) · @endif @endforeach</div>
<div class="footer">Generated by EduCore for {{ $tenant?->name }} · {{ now()->format('d M Y, H:i') }}</div>
</body>
</html>
