<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="EduCore School ERP helps Nigerian schools run admissions, academics, attendance, fees, payroll, exams, staff HR, and parent communication from one secure platform.">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#071E45">
<link rel="canonical" href="https://educoreng.online/">
<title>EduCore &mdash; School Management Platform for Nigerian Schools</title>
<link rel="icon" type="image/svg+xml" href="/brand/favicon.svg">
<link rel="preconnect" href="https://fonts.bunny.net">
<link href="https://fonts.bunny.net/css?family=plus-jakarta-sans:400,500,600,700,800,900" rel="stylesheet">
<meta property="og:type" content="website">
<meta property="og:url" content="https://educoreng.online/">
<meta property="og:site_name" content="EduCore">
<meta property="og:title" content="EduCore &mdash; School Management Platform for Nigerian Schools">
<meta property="og:description" content="Run admissions, academics, attendance, fees, payroll, exams, staff HR, and parent communication from one secure platform.">
<meta property="og:image" content="https://educoreng.online/brand/og-image.png">
<meta name="twitter:card" content="summary_large_image">
<style>
:root{--navy:#08244d;--navy2:#0d356d;--gold:#d89c22;--gold2:#f2bc45;--ink:#12213a;--muted:#66758b;--soft:#f6f8fb;--line:#e3e8ef;--white:#fff;--font:'Plus Jakarta Sans',system-ui,sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:var(--font);color:var(--ink);background:#fff;overflow-x:hidden}a{text-decoration:none;color:inherit}img,svg{display:block}.wrap{width:min(1160px,calc(100% - 40px));margin:auto}.btn{min-height:48px;padding:0 20px;border-radius:10px;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-weight:800;font-size:14px;border:1px solid transparent}.gold{background:var(--gold);color:#071d3d}.outline{border-color:#cfd8e5;background:#fff;color:var(--navy)}.nav{height:76px;border-bottom:1px solid var(--line);background:#fff;position:sticky;top:0;z-index:30}.navin{height:100%;display:flex;align-items:center;gap:28px}.logo{display:flex;align-items:center;gap:10px}.logo img{width:38px;height:38px}.logo strong{font-size:21px;color:var(--navy)}.logo strong span{color:var(--gold)}.logo small{display:block;color:#7b8798;font-size:9px}.links{margin-left:auto;display:flex;gap:25px;font-size:13px;font-weight:700;color:#526176}.actions{display:flex;gap:8px}.hamb{display:none;margin-left:auto;width:42px;height:42px;border:1px solid var(--line);border-radius:10px;background:#fff;font-size:23px;color:var(--navy)}.mobile-nav{display:none;background:#fff;border-bottom:1px solid var(--line);padding:12px 20px;position:sticky;top:68px;z-index:29}.mobile-nav.open{display:grid;gap:4px}.mobile-nav a{padding:11px;border-radius:8px;font-weight:700;font-size:13px}
.hero{padding:76px 0 64px;background:linear-gradient(180deg,#fff 0,#f8fafc 100%);position:relative;overflow:hidden}.hero:after{content:"";position:absolute;width:420px;height:420px;border-radius:50%;right:-170px;top:-160px;background:rgba(216,156,34,.08)}.hero-grid{display:grid;grid-template-columns:1fr 1fr;gap:64px;align-items:center;position:relative;z-index:1}.eyebrow{font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#996800;font-weight:900}.hero h1{font-size:clamp(44px,5vw,68px);line-height:1.02;letter-spacing:-.055em;margin:14px 0 20px;color:var(--navy)}.hero h1 span{color:var(--gold)}.lead{font-size:17px;line-height:1.75;color:var(--muted);max-width:590px}.hero-cta{display:flex;gap:10px;margin-top:28px}.proof{display:flex;gap:18px;flex-wrap:wrap;margin-top:25px;color:#68768a;font-size:10px;font-weight:800}.proof b{color:var(--gold);margin-right:5px}.visual{background:var(--navy);border-radius:26px;padding:22px;box-shadow:0 30px 70px rgba(8,36,77,.18)}.visual-top{display:flex;justify-content:space-between;align-items:center;color:#fff;margin-bottom:18px}.visual-top strong{font-size:13px}.live{font-size:9px;color:#cbd7e8}.screen{background:#f7f9fc;border-radius:16px;padding:16px}.screen-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:13px}.screen-head strong{font-size:13px;color:var(--navy)}.pill{font-size:7px;background:#fff3d5;color:#875a00;padding:5px 7px;border-radius:20px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.stat{background:#fff;border:1px solid #e5eaf1;border-radius:10px;padding:10px}.stat small{font-size:6px;color:#7a8799;text-transform:uppercase}.stat b{display:block;color:var(--navy);font-size:15px;margin-top:3px}.chart{margin-top:9px;background:#fff;border:1px solid #e5eaf1;border-radius:10px;padding:12px;height:150px;position:relative}.bars{position:absolute;inset:42px 14px 14px;display:flex;align-items:end;gap:9px}.bars i{flex:1;background:linear-gradient(var(--gold2),var(--gold));border-radius:5px 5px 0 0}.bars i:nth-child(1){height:38%}.bars i:nth-child(2){height:55%}.bars i:nth-child(3){height:47%}.bars i:nth-child(4){height:73%}.bars i:nth-child(5){height:64%}.bars i:nth-child(6){height:90%}
.trust{border-bottom:1px solid var(--line);border-top:1px solid var(--line);background:#fff}.trustin{display:grid;grid-template-columns:1.3fr repeat(6,1fr);min-height:72px;align-items:center;gap:12px}.trust strong{font-size:12px;color:var(--navy)}.trust span{font-size:10px;color:#66758b}.trust span:before{content:"•";color:var(--gold);margin-right:7px}
.section{padding:84px 0}.soft{background:var(--soft)}.dark{background:var(--navy);color:#fff}.head{max-width:700px;margin:0 auto 38px;text-align:center}.kicker{font-size:10px;letter-spacing:.13em;text-transform:uppercase;color:#a46e00;font-weight:900}.dark .kicker{color:#f3c65d}.head h2{font-size:clamp(30px,4vw,46px);line-height:1.12;letter-spacing:-.045em;color:var(--navy);margin:10px 0}.dark .head h2{color:#fff}.head p{color:var(--muted);font-size:14px;line-height:1.7}.dark .head p{color:#b8c6d9}
.modules{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.module{border:1px solid var(--line);border-radius:16px;padding:23px;background:#fff}.ico{width:42px;height:42px;border-radius:11px;background:#fff3d8;color:#9b6700;display:grid;place-items:center;font-weight:900;margin-bottom:18px}.module h3{font-size:17px;color:var(--navy);margin:0 0 8px}.module p{font-size:12px;color:var(--muted);line-height:1.65;margin:0}.module.featured{background:var(--navy);border-color:var(--navy);grid-column:span 2}.module.featured h3{color:#fff;font-size:22px}.module.featured p{color:#bdc9d8}.module.featured .ico{background:rgba(216,156,34,.15);color:#f3c65d}
.roles{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.role{border:1px solid rgba(255,255,255,.13);border-radius:15px;padding:22px;background:rgba(255,255,255,.055)}.role b{display:block;font-size:16px;margin-bottom:7px}.role p{margin:0;color:#bdc9d8;font-size:11px;line-height:1.6}.role small{display:inline-block;margin-top:15px;color:#f3c65d;font-weight:800;font-size:8px;text-transform:uppercase;letter-spacing:.08em}
.mobile-grid{display:grid;grid-template-columns:1fr .8fr;gap:70px;align-items:center}.mobile-grid h2{font-size:42px;line-height:1.08;color:var(--navy);letter-spacing:-.045em;margin:10px 0 16px}.mobile-grid p{color:var(--muted);font-size:14px;line-height:1.7}.ticks{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:24px 0}.ticks span{font-size:11px;font-weight:700;color:#526176}.ticks span:before{content:"✓";color:#16794b;margin-right:7px}.phone{width:230px;margin:auto;border:7px solid #17202d;border-radius:34px;overflow:hidden;background:#f5f7fa;box-shadow:0 28px 60px rgba(8,36,77,.22)}.phone-head{background:linear-gradient(145deg,var(--navy),var(--navy2));color:#fff;padding:28px 17px 22px}.phone-head img{width:25px;height:25px;margin-bottom:24px}.phone-head small{color:#b9c6d8}.phone-head b{display:block;font-size:17px;margin-top:3px}.phone-body{padding:13px}.phone-card{background:#fff;border:1px solid var(--line);border-radius:11px;padding:12px;margin-bottom:9px}.phone-card b{font-size:9px;color:var(--navy)}.phone-card span{display:block;color:#8390a2;font-size:7px;margin-top:4px}
.price{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);border-radius:20px;overflow:hidden;background:#fff}.price-info{padding:38px;background:var(--navy);color:#fff}.price-info h2{font-size:34px;line-height:1.1;margin:8px 0 15px}.price-info p{color:#bdc9d8;font-size:12px}.price-card{padding:38px}.price-card small{color:#6d7a8d;font-weight:800;text-transform:uppercase;font-size:9px}.big{font-size:46px;font-weight:900;color:var(--navy);letter-spacing:-.05em}.divider{height:1px;background:var(--line);margin:22px 0}.paid{font-size:32px;font-weight:900;color:var(--navy)}.price-card p{font-size:11px;color:var(--muted)}
.cta{padding:0 0 80px}.ctabox{background:linear-gradient(135deg,#061a39,var(--navy2));border-radius:20px;padding:38px;display:flex;justify-content:space-between;align-items:center;color:#fff;gap:25px}.ctabox h2{margin:0;font-size:30px}.ctabox p{margin:7px 0 0;color:#bdc9d8;font-size:12px}.ctabtns{display:flex;gap:8px}
footer{background:#030b18;color:#9ca8b9;padding:54px 0 24px}.foot{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:36px}.foot h4{color:#fff;font-size:10px;text-transform:uppercase;letter-spacing:.1em}.foot a{display:block;font-size:10px;padding:4px 0}.foot-about p{font-size:11px;max-width:330px}.contact{margin-top:14px}.contact a{font-weight:700}.copy{border-top:1px solid rgba(255,255,255,.09);margin-top:34px;padding-top:20px;font-size:9px}
@media(max-width:900px){.links,.actions{display:none}.hamb{display:block}.nav{height:68px}.hero{padding:50px 0}.hero-grid,.mobile-grid{grid-template-columns:1fr;gap:38px}.hero-copy{text-align:center}.lead{margin-left:auto;margin-right:auto}.hero-cta,.proof{justify-content:center}.trustin{grid-template-columns:repeat(3,1fr);padding:16px 0}.trust strong{grid-column:1/-1;text-align:center}.modules{grid-template-columns:1fr 1fr}.roles{grid-template-columns:1fr 1fr}.mobile-copy{text-align:center}.ticks{max-width:550px;margin:24px auto}.mobile-copy .btn{margin:auto}.foot{grid-template-columns:1fr 1fr}.foot-about{grid-column:1/-1}}
@media(max-width:600px){.wrap{width:min(100% - 28px,1160px)}.logo img{width:34px;height:34px}.logo strong{font-size:18px}.hero{padding:38px 0 42px}.hero h1{font-size:36px}.lead{font-size:14px}.hero-cta{display:grid;grid-template-columns:1fr}.hero-cta .btn{width:100%}.proof{display:grid;gap:8px}.visual{padding:12px;border-radius:18px}.screen{padding:9px}.stats{grid-template-columns:1fr 1fr}.stat:nth-child(n+3){display:none}.chart{height:115px}.trustin{grid-template-columns:1fr 1fr}.section{padding:56px 0}.head{margin-bottom:28px}.head h2{font-size:29px}.modules{grid-template-columns:1fr}.module.featured{grid-column:auto}.module{padding:20px}.roles{grid-template-columns:1fr}.mobile-grid h2{font-size:30px}.ticks{grid-template-columns:1fr}.phone{width:205px}.price{grid-template-columns:1fr}.price-info,.price-card{padding:26px 20px}.ctabox{padding:27px 20px;display:block}.ctabox h2{font-size:27px}.ctabtns{display:grid;margin-top:20px}.foot{grid-template-columns:1fr 1fr;gap:25px}.foot-about{grid-column:1/-1}}
</style>
</head>
<body>
<nav class="nav"><div class="wrap navin">
<a class="logo" href="{{ route('home') }}"><img src="/brand/educore-icon.svg" alt="EduCore"><div><strong>Edu<span>Core</span></strong><small>School ERP</small></div></a>
<div class="links"><a href="#features">Features</a><a href="#portals">Portals</a><a href="#pricing">Pricing</a><a href="#mobile">Mobile App</a><a href="mailto:support@educoreng.online">Contact</a></div>
<div class="actions"><a class="btn outline" href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}">Login</a><a class="btn gold" href="{{ route('school.register') }}">Start Free</a></div>
<button class="hamb" id="hamb" aria-label="Menu">☰</button>
</div></nav>
<div class="mobile-nav" id="mobileNav"><a href="#features">Features</a><a href="#portals">Portals</a><a href="#pricing">Pricing</a><a href="#mobile">Mobile App</a><a href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}">Login</a><a href="{{ route('school.register') }}">Start Free</a></div>
<main>
<section class="hero"><div class="wrap hero-grid">
<div class="hero-copy"><div class="eyebrow">School operations, connected</div><h1>Run your school with <span>clarity.</span></h1><p class="lead">EduCore brings academics, admissions, attendance, finance, staff management, results and parent access into one secure platform built for Nigerian schools.</p>
<div class="hero-cta"><a class="btn gold" href="{{ route('school.register') }}">Start Free →</a><a class="btn outline" href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}">Login</a></div>
<div class="proof"><span><b>✓</b> Role-based access</span><span><b>✓</b> Web + Android</span><span><b>✓</b> One integrated system</span></div></div>
<div class="visual"><div class="visual-top"><strong>EduCore Command Centre</strong><span class="live">LIVE SCHOOL OVERVIEW</span></div><div class="screen"><div class="screen-head"><strong>Good morning, Administrator</strong><span class="pill">Secure admin access</span></div><div class="stats"><div class="stat"><small>Students</small><b>1,250</b></div><div class="stat"><small>Staff</small><b>87</b></div><div class="stat"><small>Classes</small><b>56</b></div><div class="stat"><small>Fees collected</small><b>₦12.6M</b></div></div><div class="chart"><strong style="font-size:9px;color:var(--navy)">School performance overview</strong><div class="bars"><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div></div>
</div></section>
<div class="trust"><div class="wrap trustin"><strong>One platform for your entire school</strong><span>Administrators</span><span>Teachers</span><span>Accountants</span><span>Students</span><span>Parents</span><span>Officers</span></div></div>
<section class="section" id="features"><div class="wrap"><div class="head"><div class="kicker">Complete school operations</div><h2>Everything important, in one place.</h2><p>Replace disconnected records and manual processes with a coordinated system for daily school management.</p></div>
<div class="modules">
<article class="module featured"><div class="ico">↗</div><h3>See what is happening across your school.</h3><p>Live operational information brings attendance, academics, finance and administration together for faster decisions.</p></article>
<article class="module"><div class="ico">◎</div><h3>Admissions & Records</h3><p>Applications, student records, classes, transfers, promotion and graduation.</p></article>
<article class="module"><div class="ico">✓</div><h3>Attendance & Timetable</h3><p>Student and staff attendance, schedules, work hours and operational reporting.</p></article>
<article class="module"><div class="ico">₦</div><h3>Fees, Billing & Payroll</h3><p>Billing, balances, payments, expenses and staff payroll from one finance workspace.</p></article>
<article class="module"><div class="ico">A</div><h3>Academics & Results</h3><p>Lessons, score entry, examinations, report cards, broadsheets and academic records.</p></article>
<article class="module"><div class="ico">◈</div><h3>Staff & Operations</h3><p>Staff records, permissions, health, transport and other school operational workflows.</p></article>
</div></div></section>
<section class="section dark" id="portals"><div class="wrap"><div class="head"><div class="kicker">Role-specific access</div><h2>The right workspace for every user.</h2><p>Users see the tools and records appropriate to their responsibilities.</p></div><div class="roles">
<a class="role" href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}"><b>School Administrator</b><p>School-wide administration, configuration, reporting and oversight.</p><small>Administrative access →</small></a>
<div class="role"><b>Teachers & Staff</b><p>Assigned classes, attendance, score entry, timetables and daily work.</p><small>Assignment-based access</small></div>
<div class="role"><b>Accountants & Officers</b><p>Finance, payroll and function-specific operational workspaces.</p><small>Permission controlled</small></div>
<a class="role" href="{{ Route::has('student.login') ? route('student.login') : '#' }}"><b>Students</b><p>Results, attendance, timetable, fees and school information.</p><small>Personal access →</small></a>
<a class="role" href="{{ Route::has('parent.login') ? route('parent.login') : '#' }}"><b>Parents & Guardians</b><p>Linked children, results, attendance, bills, payments and updates.</p><small>Linked-child access →</small></a>
<a class="role" href="{{ Route::has('agent.portal.login') ? route('agent.portal.login') : '#' }}"><b>Agents</b><p>School registration, referrals and authorised platform workflows.</p><small>Agent portal →</small></a>
</div></div></section>
<section class="section" id="mobile"><div class="wrap mobile-grid"><div class="mobile-copy"><div class="kicker">EduCore Mobile</div><h2>School operations in your pocket.</h2><p>The native Android application gives authorised users quick access to the school functions they need while away from a desktop.</p><div class="ticks"><span>Role-specific dashboards</span><span>Attendance workflows</span><span>Score entry</span><span>Results & timetable</span><span>Staff clock-in</span><span>Web platform access</span></div><a class="btn gold" href="{{ route('app.download') }}">Download Android App</a></div>
<div class="phone"><div class="phone-head"><img src="/brand/educore-icon.svg" alt=""><small>Good morning</small><b>Welcome to EduCore</b></div><div class="phone-body"><div class="phone-card"><b>School Administrator</b><span>Authorised school access</span></div><div class="phone-card"><b>Attendance</b><span>Review today's school activity</span></div><div class="phone-card"><b>Finance</b><span>Monitor billing and collections</span></div><div class="phone-card"><b>Academics</b><span>Access scores and results</span></div></div></div>
</div></section>
<section class="section soft" id="pricing"><div class="wrap"><div class="head"><div class="kicker">Straightforward pricing</div><h2>One transparent model.</h2><p>Start at no cost, then grow with predictable termly pricing.</p></div><div class="price"><div class="price-info"><div class="kicker">Every feature included</div><h2>No confusing feature tiers.</h2><p>Schools receive the complete EduCore platform, including web and Android access.</p></div><div class="price-card"><small>Up to 50 students</small><div class="big">Free</div><div class="divider"></div><small>Above 50 students</small><div class="paid">₦300</div><p>per student / term · all EduCore features included</p><a class="btn gold" style="width:100%;margin-top:16px" href="{{ route('school.register') }}">Create School Account →</a></div></div></div></section>
<section class="cta"><div class="wrap ctabox"><div><h2>Ready to organise your school?</h2><p>Start free or sign in to an existing EduCore account.</p></div><div class="ctabtns"><a class="btn gold" href="{{ route('school.register') }}">Get Started Free</a><a class="btn outline" href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}">Login</a></div></div></section>
</main>
<footer><div class="wrap"><div class="foot"><div class="foot-about"><div class="logo"><img src="/brand/educore-icon.svg" alt=""><div><strong style="color:#fff">Edu<span>Core</span></strong></div></div><p>Integrated school management software for Nigerian schools.</p><div class="contact"><a href="tel:+2347065595768">07065595768</a><a href="https://wa.me/2347065595768">WhatsApp: +2347065595768</a><a href="mailto:support@educoreng.online">support@educoreng.online</a></div></div><div><h4>Product</h4><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#mobile">Android App</a></div><div><h4>Portals</h4><a href="{{ Route::has('admin.login') ? route('admin.login') : '#' }}">School Admin</a><a href="{{ Route::has('student.login') ? route('student.login') : '#' }}">Student</a><a href="{{ Route::has('parent.login') ? route('parent.login') : '#' }}">Parent</a></div><div><h4>Company</h4><a href="mailto:support@educoreng.online">Contact</a><a href="{{ route('legal.privacy') }}">Privacy</a><a href="{{ route('legal.terms') }}">Terms</a></div></div><div class="copy">EduCore Education Technology © {{ date('Y') }}. All rights reserved.</div></div></footer>
<script>const h=document.getElementById('hamb'),m=document.getElementById('mobileNav');h.addEventListener('click',()=>m.classList.toggle('open'));m.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>m.classList.remove('open')));</script>
</body></html>