<?php

$reference = fn (string $relationship, array $aliases = []) => ['type' => 'string', 'required' => true, 'nullable' => false, 'relationship' => $relationship, 'aliases' => $aliases];

return [
    'version' => '1.0',
    'entities' => [
        'student' => ['fields' => [
            'admission_number' => ['type' => 'string', 'required' => true, 'nullable' => false, 'tenant_unique' => true, 'aliases' => ['admission no', 'admission number', 'student id', 'student number', 'reg no']],
            'first_name' => ['type' => 'name', 'required' => true, 'nullable' => false, 'aliases' => ['firstname', 'first name', 'given name']],
            'last_name' => ['type' => 'name', 'required' => true, 'nullable' => false, 'aliases' => ['lastname', 'last name', 'surname', 'family name']],
            'middle_name' => ['type' => 'name', 'aliases' => ['middlename', 'middle name', 'other names']],
            'gender' => ['type' => 'string', 'aliases' => ['sex'], 'values' => ['male', 'female']],
            'date_of_birth' => ['type' => 'date', 'aliases' => ['dob', 'birth date', 'date of birth']],
            'state_of_origin' => ['type' => 'string', 'aliases' => ['state', 'origin state']],
            'lga_of_origin' => ['type' => 'string', 'aliases' => ['lga', 'local government']],
            'religion' => ['type' => 'string', 'aliases' => ['faith']],
            'blood_group' => ['type' => 'string', 'aliases' => ['blood type']],
            'genotype' => ['type' => 'string'],
            'status' => ['type' => 'string', 'aliases' => ['student status'], 'values' => ['applicant', 'active', 'suspended', 'graduated', 'withdrawn']],
            'admission_date' => ['type' => 'date', 'aliases' => ['date admitted', 'enrolment date']],
            'graduation_date' => ['type' => 'date', 'aliases' => ['completion date']],
            'current_class_arm' => ['type' => 'string', 'relationship' => 'class_arm', 'aliases' => ['class', 'current class', 'class arm']],
        ]],
        'guardian' => ['fields' => [
            'first_name' => ['type' => 'name', 'required' => true, 'aliases' => ['guardian first name', 'parent first name']],
            'last_name' => ['type' => 'name', 'required' => true, 'aliases' => ['guardian surname', 'parent surname']],
            'phone' => ['type' => 'phone', 'aliases' => ['mobile', 'telephone', 'phone number']],
            'email' => ['type' => 'email', 'aliases' => ['email address']],
            'occupation' => ['type' => 'string'], 'address' => ['type' => 'string'],
            'relationship' => ['type' => 'string', 'aliases' => ['relationship to student', 'parent type']],
            'student_admission_number' => $reference('student', ['student id', 'ward admission number']),
            'is_primary_contact' => ['type' => 'boolean', 'aliases' => ['primary contact']],
        ]],
        'staff' => ['fields' => [
            'staff_id' => ['type' => 'string', 'tenant_unique' => true, 'aliases' => ['employee id', 'staff number', 'employee number']],
            'name' => ['type' => 'name', 'required' => true, 'nullable' => false, 'aliases' => ['full name', 'staff name', 'employee name']],
            'email' => ['type' => 'email', 'required' => true, 'nullable' => false, 'tenant_unique' => true, 'aliases' => ['email address', 'work email']],
            'phone' => ['type' => 'phone', 'aliases' => ['mobile', 'phone number']],
            'role' => ['type' => 'string', 'required' => true, 'aliases' => ['staff role', 'designation']],
            'gender' => ['type' => 'string', 'aliases' => ['sex'], 'values' => ['male', 'female', 'other']],
            'date_of_birth' => ['type' => 'date', 'aliases' => ['dob', 'birth date']],
            'address' => ['type' => 'string'], 'qualification' => ['type' => 'string'],
            'employment_status' => ['type' => 'string', 'aliases' => ['staff status']],
            'employment_started_at' => ['type' => 'date', 'aliases' => ['employment date', 'hire date']],
            'employment_ended_at' => ['type' => 'date', 'aliases' => ['exit date']],
            'exit_reason' => ['type' => 'string'], 'is_active' => ['type' => 'boolean', 'aliases' => ['active']],
        ]],
        'academic_session' => ['fields' => [
            'name' => ['type' => 'string', 'required' => true, 'tenant_unique' => true, 'aliases' => ['session', 'academic year', 'school year']],
            'is_current' => ['type' => 'boolean', 'aliases' => ['current session']],
        ]],
        'term' => ['fields' => [
            'session' => $reference('academic_session', ['academic session', 'school year']),
            'name' => ['type' => 'string', 'required' => true, 'aliases' => ['term', 'term name']],
            'start_date' => ['type' => 'date', 'aliases' => ['starts on']], 'end_date' => ['type' => 'date', 'aliases' => ['ends on']],
            'next_term_begins' => ['type' => 'date', 'aliases' => ['resumption date']], 'is_current' => ['type' => 'boolean'],
        ]],
        'class_level' => ['fields' => [
            'name' => ['type' => 'string', 'required' => true, 'tenant_unique' => true, 'aliases' => ['level', 'class level', 'grade']],
            'section' => ['type' => 'string', 'values' => ['junior', 'senior', 'general']], 'order_index' => ['type' => 'integer', 'aliases' => ['sort order']],
        ]],
        'class_arm' => ['fields' => [
            'class_level' => $reference('class_level', ['level', 'grade']),
            'name' => ['type' => 'string', 'required' => true, 'aliases' => ['arm', 'class arm']],
            'academic_track' => ['type' => 'string', 'relationship' => 'academic_track', 'aliases' => ['track', 'stream']],
            'form_tutor_email' => ['type' => 'email', 'relationship' => 'staff', 'aliases' => ['form teacher', 'class teacher email']],
        ]],
        'subject' => ['fields' => [
            'name' => ['type' => 'string', 'required' => true, 'aliases' => ['subject name']],
            'code' => ['type' => 'string', 'tenant_unique' => true, 'aliases' => ['subject code']],
            'is_active' => ['type' => 'boolean', 'aliases' => ['active']],
        ]],
        'assessment_type' => ['fields' => [
            'term' => $reference('term', ['term name']), 'name' => ['type' => 'string', 'required' => true, 'aliases' => ['assessment', 'component']],
            'weight_percentage' => ['type' => 'decimal', 'aliases' => ['weight', 'percentage']], 'objective_max' => ['type' => 'decimal'],
            'theory_max' => ['type' => 'decimal'], 'is_exam' => ['type' => 'boolean', 'aliases' => ['exam']],
        ]],
        'grading_system' => ['fields' => [
            'class_level' => $reference('class_level', ['level', 'grade level', 'class']),
            'grade_letter' => ['type' => 'string', 'required' => true, 'aliases' => ['grade', 'letter grade']],
            'min_score' => ['type' => 'decimal', 'required' => true, 'aliases' => ['minimum', 'minimum score', 'score from']],
            'max_score' => ['type' => 'decimal', 'required' => true, 'aliases' => ['maximum', 'maximum score', 'score to']],
            'remark' => ['type' => 'string', 'aliases' => ['comment', 'description']],
            'is_pass_grade' => ['type' => 'boolean', 'aliases' => ['pass grade', 'is pass']],
            'grade_point' => ['type' => 'decimal', 'aliases' => ['point', 'gpa point']],
        ]],
        'student_enrollment' => ['fields' => [
            'student_admission_number' => $reference('student', ['admission number', 'student id']),
            'class_arm' => $reference('class_arm', ['class', 'arm']), 'session' => $reference('academic_session', ['academic session']),
            'term' => $reference('term', ['term name']), 'start_date' => ['type' => 'date'], 'end_date' => ['type' => 'date'],
            'is_current' => ['type' => 'boolean'], 'status' => ['type' => 'string'], 'ended_reason' => ['type' => 'string'],
        ]],
        'score' => ['fields' => [
            'student_admission_number' => $reference('student', ['admission number', 'student id']), 'subject_code' => $reference('subject', ['subject']),
            'assessment_type' => $reference('assessment_type', ['assessment', 'component']), 'term' => $reference('term', ['term name']),
            'session' => $reference('academic_session', ['academic session']), 'score' => ['type' => 'decimal', 'required' => true, 'aliases' => ['mark', 'marks']],
            'objective_score' => ['type' => 'decimal'], 'theory_score' => ['type' => 'decimal'], 'entered_at' => ['type' => 'date'],
        ]],
        'subject_registration' => ['fields' => [
            'student_admission_number' => $reference('student', ['admission number', 'student id']),
            'class_level' => $reference('class_level', ['level', 'grade']), 'subject_code' => $reference('subject', ['subject']),
            'session' => $reference('academic_session', ['academic session']), 'term' => ['type' => 'string', 'relationship' => 'term', 'aliases' => ['term name']],
            'selection_type' => ['type' => 'string', 'values' => ['compulsory', 'elective']], 'is_active' => ['type' => 'boolean'],
        ]],
        'attendance' => ['fields' => [
            'student_admission_number' => $reference('student', ['admission number', 'student id']), 'class_arm' => $reference('class_arm', ['class']),
            'term' => $reference('term', ['term name']), 'attendance_date' => ['type' => 'date', 'required' => true, 'nullable' => false, 'aliases' => ['date']],
            'status' => ['type' => 'string', 'required' => true, 'values' => ['present', 'absent', 'late', 'excused']], 'remark' => ['type' => 'string'],
        ]],
        'termly_summary' => ['fields' => [
            'student_admission_number' => $reference('student', ['admission number', 'student id']), 'class_arm' => $reference('class_arm', ['class']),
            'term' => $reference('term', ['term name']), 'session' => $reference('academic_session', ['academic session']),
            'total_score' => ['type' => 'decimal'], 'final_average' => ['type' => 'decimal', 'aliases' => ['average']],
            'position_in_class' => ['type' => 'integer', 'aliases' => ['position']], 'total_students_in_class' => ['type' => 'integer'],
            'subjects_offered' => ['type' => 'integer'], 'subjects_failed' => ['type' => 'integer'],
            'promotion_status' => ['type' => 'string', 'values' => ['pending', 'promoted', 'repeat', 'graduated']],
            'form_tutor_remark' => ['type' => 'string'], 'principal_remark' => ['type' => 'string'],
        ]],
        'invoice' => ['fields' => [
            'invoice_number' => ['type' => 'string', 'required' => true, 'tenant_unique' => true, 'aliases' => ['invoice no']],
            'student_admission_number' => $reference('student', ['student id']), 'term' => $reference('term'), 'session' => $reference('academic_session'),
            'total_amount' => ['type' => 'money', 'required' => true, 'aliases' => ['amount', 'invoice total']], 'amount_paid' => ['type' => 'money'],
            'status' => ['type' => 'string', 'values' => ['unpaid', 'partially_paid', 'paid']], 'due_date' => ['type' => 'date'], 'notes' => ['type' => 'string'],
        ]],
        'payment' => ['fields' => [
            'gateway_reference' => ['type' => 'string', 'required' => true, 'tenant_unique' => true, 'aliases' => ['payment reference', 'transaction reference']],
            'invoice_number' => ['type' => 'string', 'required' => true, 'relationship' => 'invoice', 'aliases' => ['invoice no']],
            'student_admission_number' => $reference('student', ['student id']), 'amount_paid' => ['type' => 'money', 'required' => true, 'aliases' => ['amount']],
            'currency' => ['type' => 'string', 'required' => true, 'aliases' => ['currency code']], 'status' => ['type' => 'string', 'required' => true, 'values' => ['pending', 'success', 'failed', 'reversed']],
            'gateway' => ['type' => 'string'], 'paid_by_name' => ['type' => 'name'], 'paid_by_phone' => ['type' => 'phone'], 'paid_at' => ['type' => 'date'],
        ]],
        'fee_structure' => ['fields' => [
            'fee_category' => ['type' => 'string', 'required' => true, 'relationship' => 'fee_category', 'aliases' => ['fee name', 'category']],
            'class_level' => $reference('class_level', ['class', 'level']), 'term' => $reference('term', ['term name']),
            'amount' => ['type' => 'money', 'required' => true], 'currency' => ['type' => 'string', 'required' => true], 'is_active' => ['type' => 'boolean'],
        ]],
    ],
];
