@extends('layouts.app')
@section('title', 'Exam Security Acknowledgement')
@section('page-title', 'CBT Examination')
@push('styles')
<style>
.ack-shell{max-width:760px;margin:24px auto}.ack-card{background:#fff;border:1px solid var(--border);border-radius:16px;overflow:hidden;box-shadow:0 12px 32px rgba(15,23,42,.08)}.ack-head{padding:26px;background:linear-gradient(135deg,#0B234B,#153E75);color:#fff}.ack-head small{font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#FBBF24}.ack-head h1{font-size:23px;margin:7px 0}.ack-head p{font-size:12px;opacity:.8}.ack-body{padding:24px}.exam-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:20px}.datum{border:1px solid var(--border);border-radius:10px;padding:12px}.datum strong{display:block;font-size:15px;color:var(--midnight)}.datum span{font-size:10px;color:var(--slate)}.rules{border:1px solid #BFDBFE;background:#EFF6FF;border-radius:12px;padding:16px;margin-bottom:18px}.rules h2{font-size:13px;color:#1E3A8A;margin:0 0 10px}.rules li{font-size:12px;color:#334155;margin:7px 0}.ack-check{display:flex;gap:10px;align-items:flex-start;padding:14px;border:1px solid var(--border);border-radius:10px;font-size:12px;color:var(--midnight)}.ack-check input{margin-top:2px}.actions{display:flex;gap:10px;justify-content:flex-end;margin-top:18px}.btn{border:0;border-radius:9px;padding:11px 17px;font:600 12px inherit;text-decoration:none;cursor:pointer}.btn-primary{background:var(--indigo);color:#fff}.btn-light{border:1px solid var(--border);background:#fff;color:var(--midnight)}.alert{background:#FEF2F2;border:1px solid #FECACA;color:#991B1B;padding:11px;border-radius:9px;margin-bottom:14px;font-size:12px}@media(max-width:600px){.ack-shell{margin:0}.ack-card{border-radius:10px}.exam-grid{grid-template-columns:1fr}.ack-body,.ack-head{padding:18px}.actions{flex-direction:column-reverse}.btn{text-align:center}}
</style>
@endpush
@section('content')
<div class="ack-shell"><div class="ack-card"><div class="ack-head"><small>{{ $retake ? 'Authorized retake · Attempt '.$retake->attempt_number : 'Secure examination' }}</small><h1>{{ $exam->title }}</h1><p>{{ $exam->questionBank->subject->name ?? '' }} · {{ $exam->assignedClassNames() }}</p></div><div class="ack-body">
@if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif
<div class="exam-grid"><div class="datum"><strong>{{ $exam->duration_minutes }} minutes</strong><span>Time allowed</span></div><div class="datum"><strong>{{ $exam->sections()->where('is_active',true)->count() }}</strong><span>Exam sections</span></div><div class="datum"><strong>{{ number_format($exam->total_marks,1) }}</strong><span>Maximum marks</span></div></div>
<div class="rules"><h2>Examination integrity notice</h2><ul><li>Keep this examination page visible and active until you submit.</li><li>Leaving the page, changing tabs, minimizing the browser, or exiting required full-screen mode is recorded.</li>@if($exam->focus_loss_policy==='submit' && $exam->max_focus_losses===0)<li><strong>The first prohibited focus-loss event will submit your current answers automatically.</strong></li>@endif<li>Answers are saved periodically. After final submission, no answer can be changed.</li><li>A retake is only possible when a school administrator records a reason and authorizes it.</li></ul></div>
<form method="POST" action="{{ route('cbt.exams.begin',$exam) }}">@csrf<label class="ack-check"><input type="checkbox" name="integrity_acknowledged" value="1" required><span>I have read and understood the examination rules. I consent to the recording of integrity events and understand that a prohibited event may submit my attempt.</span></label><div class="actions"><a class="btn btn-light" href="{{ route('student.portal.exams') }}">Cancel</a><button class="btn btn-primary">Acknowledge and begin</button></div></form>
</div></div></div>
@endsection
