@extends('layouts.app')
@section('title','CBT Retake Control')
@section('page-title','CBT Retake Control')
@push('styles')
<style>
.shell{max-width:1280px;margin:auto}.head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.head h1{font-size:22px;color:var(--midnight);margin:0 0 4px}.muted{font-size:11px;color:var(--slate)}.card{background:#fff;border:1px solid var(--border);border-radius:12px;overflow:hidden}.filters{display:grid;grid-template-columns:2fr 1fr 1fr auto;gap:9px;padding:14px;border-bottom:1px solid var(--border)}.control{width:100%;border:1px solid var(--border);border-radius:8px;padding:9px 10px;font:inherit;font-size:12px;background:#F8FAFC}.btn{border:0;border-radius:8px;padding:9px 12px;font:700 11px inherit;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.btn-primary{background:var(--indigo);color:#fff}.btn-light{background:#fff;border:1px solid var(--border);color:var(--midnight)}.btn-danger{background:#FEF2F2;color:#B91C1C;border:1px solid #FECACA}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:900px}th,td{padding:11px 13px;border-bottom:1px solid var(--border);text-align:left;font-size:11px}th{background:#F8FAFC;color:var(--slate);text-transform:uppercase;font-size:9px;letter-spacing:.05em}.status{display:inline-flex;padding:3px 8px;border-radius:20px;background:#F1F5F9;color:var(--slate);font-weight:700}.row-actions{display:flex;gap:6px;flex-wrap:wrap}.inline-reason{display:flex;gap:5px}.inline-reason input{width:150px}.alert{padding:11px;border-radius:8px;margin-bottom:12px;background:#ECFDF5;border:1px solid #A7F3D0;color:#065F46;font-size:12px}@media(max-width:760px){.filters{grid-template-columns:1fr}.head{display:block}.table-wrap{margin:0 -1px}}
</style>
@endpush
@section('content')
<div class="shell"><div class="head"><div><h1>Retake control</h1><div class="muted">Authorize one numbered attempt at a time. Previous attempts remain preserved.</div></div><a class="btn btn-light" href="{{ route('cbt.exams') }}">Back to exams</a></div>@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
@if($pendingAuthorizations->count())<div class="card" style="margin-bottom:12px"><div style="padding:13px;border-bottom:1px solid var(--border)"><strong>Unused authorizations</strong></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Exam</th><th>Attempt</th><th>Authorized by</th><th>Reason</th><th></th></tr></thead><tbody>@foreach($pendingAuthorizations as $authorization)<tr><td>{{ $authorization->student->full_name }}</td><td>{{ $authorization->exam->title }}</td><td>#{{ $authorization->attempt_number }}</td><td>{{ $authorization->authorizer->name }}</td><td>{{ $authorization->reason }}</td><td><form class="inline-reason" method="POST" action="{{ route('cbt.retakes.revoke',$authorization) }}">@csrf<input class="control" name="reason" required minlength="5" placeholder="Revocation reason"><button class="btn btn-danger">Revoke</button></form></td></tr>@endforeach</tbody></table></div></div>@endif
<div class="card"><form class="filters" method="GET"><input class="control" name="student" value="{{ request('student') }}" placeholder="Student name or admission number"><select class="control" name="exam_id"><option value="">All exams</option>@foreach($exams as $exam)<option value="{{ $exam->id }}" @selected(request('exam_id')==$exam->id)>{{ $exam->title }}</option>@endforeach</select><select class="control" name="status"><option value="">All statuses</option>@foreach(['in_progress','submitted','auto_submitted','graded','invalidated','cancelled'] as $status)<option @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select><button class="btn btn-primary">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Student</th><th>Exam</th><th>Attempt</th><th>Status</th><th>Score</th><th>Integrity</th><th>Control</th></tr></thead><tbody>@forelse($attempts as $attempt)<tr id="attempt-{{ $attempt->id }}"><td><strong>{{ $attempt->student->full_name }}</strong><div class="muted">{{ $attempt->student->admission_number }}</div></td><td>{{ $attempt->exam->title }}<div class="muted">{{ $attempt->exam->questionBank->subject->name ?? '' }}</div></td><td>#{{ $attempt->attempt_number }} @if($attempt->is_active_result)<div class="muted">Active result</div>@endif</td><td><span class="status">{{ str_replace('_',' ',$attempt->status) }}</span></td><td>{{ $attempt->raw_score===null?'Pending':$attempt->raw_score.'/'.$attempt->maximum_score }}</td><td>{{ $attempt->focus_loss_count }} event(s)</td><td><div class="row-actions">
@if($attempt->isFinal())<form class="inline-reason" method="POST" action="{{ route('cbt.retakes.authorize',[$attempt->exam,$attempt->student]) }}">@csrf<input class="control" name="reason" required minlength="5" placeholder="Retake reason"><button class="btn btn-primary">Authorize</button></form>@endif
@if(!$attempt->isInvalid() && $attempt->isFinal())<form class="inline-reason" method="POST" action="{{ route('cbt.attempts.invalidate',$attempt) }}">@csrf<input class="control" name="reason" required minlength="5" placeholder="Invalidation reason"><button class="btn btn-danger">Invalidate</button></form>@endif
</div></td></tr>@empty<tr><td colspan="7" style="text-align:center;padding:30px;color:var(--slate)">No attempts match the filters.</td></tr>@endforelse</tbody></table></div></div><div style="margin-top:12px">{{ $attempts->links() }}</div></div>
@endsection
