@extends('layouts.app')
@section('title','Staff Onboarding')
@section('page-title','Staff Onboarding')
@push('styles')<style>.box{background:#fff;border:1px solid var(--border);border-radius:12px;padding:16px;margin-bottom:16px}.linkrow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.join{flex:1 1 360px;padding:10px 12px;border:1px solid var(--border);border-radius:8px;background:#F8FAFC;overflow-wrap:anywhere}.btn{display:inline-flex;align-items:center;justify-content:center;padding:9px 14px;border-radius:8px;border:0;text-decoration:none;font-size:12px;font-weight:700;cursor:pointer}.primary{background:var(--indigo);color:#fff}.ghost{background:#fff;border:1px solid var(--border);color:var(--midnight)}.danger{background:#FEF2F2;color:#B91C1C;border:1px solid #FECACA}.grid{display:grid;gap:10px}.item{border:1px solid var(--border);border-radius:10px;padding:12px}.top{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.meta{font-size:11px;color:var(--slate-light);margin-top:4px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.role{min-width:210px;padding:9px;border:1px solid var(--border);border-radius:8px}.pending{color:#92400E}.approved{color:#047857}.rejected{color:#B91C1C}@media(max-width:700px){.linkrow,.actions{align-items:stretch}.join,.btn,.role{width:100%}.item{padding:10px}}</style>@endpush
@section('content')
@if(session('success'))<div class="box" style="background:#ECFDF5;color:#047857">{{ session('success') }}</div>@endif
@if($errors->any())<div class="box" style="background:#FEF2F2;color:#B91C1C">{{ $errors->first() }}</div>@endif
<div class="box"><h3 style="margin-top:0">Share Staff Profile Link</h3><p style="font-size:12px;color:var(--slate)">Share this short tenant-specific URL with staff. Profiles remain pending until an administrator approves them.</p><div class="linkrow"><div class="join" id="joinUrl">{{ $joinUrl }}</div><button class="btn primary" type="button" onclick="navigator.clipboard.writeText(document.getElementById('joinUrl').innerText)">Copy Link</button><form method="POST" action="{{ route('staff.onboarding.rotate') }}">@csrf<button class="btn ghost" type="submit">Generate New Link</button></form></div></div>
<div class="box"><h3 style="margin-top:0">Profile Submissions</h3><div class="grid">@forelse($submissions as $submission)<div class="item"><div class="top"><div><strong>{{ $submission->name }}</strong><div class="meta">{{ $submission->email }} · {{ ucfirst($submission->gender) }} · {{ $submission->qualification }} · {{ $submission->position_title ?: 'Position not supplied' }}</div></div><strong class="{{ $submission->status }}">{{ strtoupper($submission->status) }}</strong></div>@if($submission->status==='pending')<div class="actions"><form method="POST" action="{{ route('staff.onboarding.approve',$submission) }}" style="display:flex;gap:8px;flex-wrap:wrap;flex:1">@csrf<select name="role" class="role" required><option value="">Assign system role</option>@foreach($roleLabels as $role=>$label)<option value="{{ $role }}">{{ $label }}</option>@endforeach</select><button class="btn primary" type="submit">Approve & Activate</button></form><form method="POST" action="{{ route('staff.onboarding.reject',$submission) }}">@csrf<button class="btn danger" type="submit">Reject</button></form></div>@endif</div>@empty<div style="font-size:12px;color:var(--slate-light)">No staff profile submissions yet.</div>@endforelse</div><div style="margin-top:12px">{{ $submissions->links() }}</div></div>
@endsection