<?php
namespace App\Services\Curriculum;
use App\Models\CurriculumFragment;use App\Models\CurriculumSource;use App\Models\RepositoryImport;use App\Models\RepositoryImportItem;use App\Models\Subject;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use ZipArchive;
class AcademicRepositoryIngestionService{
 /** Sized for the verified Lesson_Notes archive while retaining ZIP-bomb safeguards. */
 public const MAX_FILES=8000;public const MAX_EXPANDED=3221225472;
 public function ingest(UploadedFile $file,array $meta,int $actor):RepositoryImport{
  $ext=strtolower($file->getClientOriginalExtension());$import=RepositoryImport::create(['filename'=>$file->getClientOriginalName(),'format'=>$ext,'uploaded_by'=>$actor,'status'=>'processing','started_at'=>now()]);
  try{if($ext==='zip')$this->zip($file,$meta,$actor,$import);elseif(in_array($ext,['xlsx','xls'],true))$this->xlsx($file,$meta,$actor,$import);else $this->document($file->getRealPath(),$file->getClientOriginalName(),$file->getMimeType(),$meta,$actor,$import);
   $import->update(['status'=>$import->failed?'completed_with_errors':'completed','completed_at'=>now()]);
  }catch(\Throwable $e){$import->update(['status'=>'failed','failed'=>DB::raw('failed + 1'),'metadata'=>['error'=>Str::limit($e->getMessage(),500)]]);throw $e;}return $import->fresh();
 }
 private function document(string $path,string $name,string $mime,array $meta,int $actor,RepositoryImport $import,?string $relative=null):void{
  $ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['docx','doc','pdf'],true)){$this->item($import,$relative?:$name,'unsupported','Unsupported archive entry.');return;}
  $checksum=hash_file('sha256',$path);$duplicate=CurriculumSource::whereNull('tenant_id')->where('checksum',$checksum)->first();if($duplicate){$import->increment('duplicates');$this->item($import,$relative?:$name,'duplicate','Matching checksum already exists.',$duplicate->id);return;}
  [$raw,$locator]=$ext==='docx'?$this->docx($path):($ext==='doc'?$this->doc($path):$this->pdf($path));$meta=$this->infer($relative?:$name,$meta);$clean=$this->clean($raw);$stored=Storage::disk('local')->putFileAs('academic-repository/originals',new \Illuminate\Http\File($path),Str::uuid().'.'.$ext);
  $status=mb_strlen($clean)>=80?'extracted':'failed';$source=DB::transaction(function()use($meta,$actor,$name,$mime,$checksum,$stored,$raw,$clean,$status,$ext){$s=CurriculumSource::create(['tenant_id'=>null,'subject_id'=>$meta['subject_id']??null,'class_level_id'=>$meta['curriculum_level_id']??null,'source_class_level_id'=>$meta['source_class_level_id']??null,'curriculum_level_id'=>$meta['curriculum_level_id']??null,'term_id'=>$meta['term_id']??null,'week_number'=>$meta['week_number']??null,'authority'=>$meta['authority']??'OTHER','source_type'=>$meta['source_type']??'curriculum_document','title'=>$meta['title']??pathinfo($name,PATHINFO_FILENAME),'original_filename'=>basename($name),'version'=>$meta['version']??date('Y'),'source_file_path'=>$stored,'mime_type'=>$mime,'file_size'=>filesize($stored?Storage::disk('local')->path($stored):$name),'checksum'=>$checksum,'raw_text'=>$raw,'cleaned_text'=>$clean,'extraction_status'=>$status,'index_status'=>$status==='extracted'?'indexed':'failed','is_official'=>(bool)($meta['is_official']??false),'is_active'=>false,'needs_review'=>true,'review_status'=>'pending','created_by'=>$actor,'rights_status'=>$meta['rights_status']??'institution_authorised','metadata'=>['format'=>$ext]]);if($status==='extracted')foreach($this->chunks($clean)as$i=>$chunk)CurriculumFragment::create(['curriculum_source_id'=>$s->id,'subject_id'=>$s->subject_id,'class_level_id'=>$s->curriculum_level_id,'topic'=>$meta['topic']??$s->title,'subtopic'=>$meta['subtopic']??null,'content'=>$chunk,'source_locator'=>$ext==='pdf'?'Extracted page text':'Document section '.($i+1),'sequence'=>$i]);return $s;});
  $import->increment('discovered');$status==='extracted'?$import->increment('imported'):$import->increment('failed');$import->increment('needs_review');$this->item($import,$relative?:$name,$status==='extracted'?'needs_review':'failed',$status==='extracted'?'Extracted and indexed; verify metadata.':'No readable text; scanned PDF may require OCR.',$source->id);
 }
 private function zip(UploadedFile $file,array $meta,int $actor,RepositoryImport $import):void{$z=new ZipArchive;if($z->open($file->getRealPath())!==true)throw new \RuntimeException('Invalid ZIP archive.');$count=$z->numFiles;$expanded=0;if($count>self::MAX_FILES)throw new \RuntimeException('Archive file-count limit exceeded (maximum 8,000 files).');for($i=0;$i<$count;$i++){$st=$z->statIndex($i);$name=str_replace('\\','/',$st['name']);$expanded+=(int)$st['size'];if($expanded>self::MAX_EXPANDED)throw new \RuntimeException('Archive expanded-size limit exceeded (maximum 3 GB).');if(str_starts_with($name,'/')||preg_match('#(^|/)\.\.(/|$)#',$name)||preg_match('/^[A-Za-z]:/',$name))throw new \RuntimeException('Unsafe ZIP path detected.');if(str_ends_with($name,'/'))continue;$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));if(!in_array($ext,['docx','doc','pdf','xlsx','xls'],true)){$this->item($import,$name,'unsupported','Only DOCX, DOC, PDF, XLSX and XLS entries are supported.');continue;}$tmp=tempnam(sys_get_temp_dir(),'edurepo_');file_put_contents($tmp,$z->getFromIndex($i));$inferred=$this->infer($name,$meta);if(in_array($ext,['xlsx','xls'],true))$this->xlsxPath($tmp,$name,$inferred,$actor,$import);else$this->document($tmp,basename($name),$this->mime($ext),$inferred,$actor,$import,$name);@unlink($tmp);}$z->close();}
 private function xlsx(UploadedFile $file,array $meta,int $actor,RepositoryImport $import):void{$this->xlsxPath($file->getRealPath(),$file->getClientOriginalName(),$meta,$actor,$import);}
 private function xlsxPath(string $path,string $name,array $meta,int $actor,RepositoryImport $import):void{[$headers,$rows]=$this->sheet($path);$import->increment('discovered',count($rows));$mapping=$meta['column_mapping']??[];foreach($rows as$n=>$row){$values=[];foreach($mapping as$field=>$header){$idx=array_search($header,$headers,true);if($idx!==false)$values[$field]=$row[$idx]??null;}if(empty($values['content'])||empty($values['title'])){$import->increment('failed');$this->item($import,$name.' row '.($n+2),'failed','Title and Content mappings are required.');continue;}$checksum=hash('sha256',$values['content']);if(CurriculumSource::whereNull('tenant_id')->where('checksum',$checksum)->exists()){$import->increment('duplicates');continue;}$s=CurriculumSource::create(['tenant_id'=>null,'subject_id'=>$meta['subject_id']??null,'curriculum_level_id'=>$meta['curriculum_level_id']??null,'authority'=>$values['authority']??'OTHER','source_type'=>$values['resource_type']??'curriculum_document','title'=>$values['title'],'original_filename'=>$name,'version'=>$values['source_year']??date('Y'),'checksum'=>$checksum,'raw_text'=>$values['content'],'cleaned_text'=>$this->clean($values['content']),'extraction_status'=>'extracted','index_status'=>'indexed','is_active'=>false,'needs_review'=>true,'review_status'=>'pending','created_by'=>$actor,'rights_status'=>'institution_authorised','metadata'=>['spreadsheet_row'=>$n+2]]);foreach($this->chunks($s->cleaned_text)as$i=>$chunk)CurriculumFragment::create(['curriculum_source_id'=>$s->id,'subject_id'=>$s->subject_id,'class_level_id'=>$s->curriculum_level_id,'topic'=>$values['topic']??$s->title,'subtopic'=>$values['subtopic']??null,'content'=>$chunk,'source_locator'=>'Spreadsheet row '.($n+2),'sequence'=>$i]);$import->increment('imported');$import->increment('needs_review');}}
 private function docx(string$p):array{$z=new ZipArchive;if($z->open($p)!==true)return['',''];$xml=$z->getFromName('word/document.xml')?:'';$z->close();return[html_entity_decode(strip_tags(str_replace(['</w:p>','</w:tr>'],["\n","\n"],$xml)),ENT_QUOTES|ENT_XML1,'UTF-8'),'document'];}
 private function doc(string$p):array{$raw=file_get_contents($p)?:'';if(str_starts_with($raw,'{\\rtf'))$raw=preg_replace('/\\\\[a-z]+-?\d* ?|[{}]/i',' ',$raw);else$raw=preg_replace('/[^\x20-\x7E\r\n]/',' ',$raw);return[$raw,'legacy DOC'];}
 private function pdf(string$p):array{$raw=file_get_contents($p);preg_match_all('/\(([^()]*(?:\\.[^()]*)*)\)\s*Tj/s',$raw,$m);$text=implode("\n",array_map(fn($v)=>stripcslashes($v),$m[1]??[]));return[$text,'pages'];}
 private function sheet(string$p):array{$sheet=\PhpOffice\PhpSpreadsheet\IOFactory::load($p)->getActiveSheet();$rows=$sheet->toArray('',true,true,false);return[array_map('trim',array_shift($rows)?:[]),$rows];}
 private function clean(string$t):string{return trim(preg_replace('/\s+/u',' ',html_entity_decode(strip_tags($t),ENT_QUOTES|ENT_HTML5,'UTF-8')));}private function chunks(string$t):array{return array_values(array_filter(str_split($t,2200),fn($v)=>trim($v)!==''));}private function mime(string$e):string{return['pdf'=>'application/pdf','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document','xlsx'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','xls'=>'application/vnd.ms-excel'][$e];}
 private function infer(string$p,array$m):array{$parts=array_values(array_filter(explode('/',str_replace('\\','/',$p))));$subject=$parts[count($parts)-3]??$parts[0]??null;if(in_array(strtolower((string)$subject),['lesson_notes','lesson notes'],true))$subject=$parts[1]??null;$context=$parts[count($parts)-2]??'';$file=pathinfo(end($parts),PATHINFO_FILENAME);$m['title']??=preg_replace(['/^\d+\s*-\s*/','/\b(?:20\d{2}\s+)?week\s*\d+(?:\s*[&-]\s*\d+)?\s*[-:–]?\s*/i'],'',$file);if(preg_match('/week\s*(\d+)/i',$p,$x))$m['week_number']=(int)$x[1];$m['subject_id']=$m['subject_id']??Subject::query()->whereRaw('LOWER(name)=?',[mb_strtolower(trim((string)$subject))])->value('id');$m['source_type']=$m['source_type']??'lesson_note';$m['metadata']=array_filter(['subject_label'=>$subject,'class_label'=>$context]);return$m;}private function item(RepositoryImport$i,string$p,string$s,string$m,?int$id=null):void{RepositoryImportItem::create(['repository_import_id'=>$i->id,'curriculum_source_id'=>$id,'relative_path'=>$p,'status'=>$s,'message'=>$m]);}
}
