<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
Schema::table('lesson_plans',function(Blueprint $t){$t->unsignedBigInteger('curriculum_level_id')->nullable()->after('class_level_id');$t->string('delivery_type',30)->default('regular')->after('curriculum_type');$t->timestamp('published_at')->nullable()->after('approved_at');});
Schema::table('curriculum_sources',function(Blueprint $t){$t->unsignedBigInteger('source_class_level_id')->nullable();$t->unsignedBigInteger('curriculum_level_id')->nullable();$t->unsignedBigInteger('term_id')->nullable();$t->unsignedTinyInteger('week_number')->nullable();$t->string('original_filename')->nullable();$t->string('mime_type',150)->nullable();$t->unsignedBigInteger('file_size')->nullable();$t->longText('raw_text')->nullable();$t->longText('cleaned_text')->nullable();$t->string('extraction_status',30)->default('pending');$t->string('index_status',30)->default('pending');$t->boolean('needs_review')->default(true);$t->timestamp('archived_at')->nullable();});
Schema::create('curriculum_topics',function(Blueprint $t){$t->id();$t->unsignedBigInteger('subject_id');$t->unsignedBigInteger('curriculum_level_id');$t->unsignedBigInteger('term_id')->nullable();$t->unsignedTinyInteger('recommended_week')->nullable();$t->string('topic');$t->json('subtopics')->nullable();$t->json('learning_objectives')->nullable();$t->json('keywords')->nullable();$t->string('curriculum_source')->nullable();$t->string('curriculum_year',20)->nullable();$t->string('status',20)->default('active');$t->unsignedBigInteger('created_by');$t->timestamps();$t->index(['subject_id','curriculum_level_id','status']);});
Schema::create('repository_imports',function(Blueprint $t){$t->id();$t->string('filename');$t->string('format',10);$t->unsignedBigInteger('uploaded_by');$t->string('status',30)->default('queued');foreach(['discovered','imported','duplicates','failed','needs_review'] as $c)$t->unsignedInteger($c)->default(0);$t->json('mapping')->nullable();$t->json('metadata')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();});
Schema::create('repository_import_items',function(Blueprint $t){$t->id();$t->unsignedBigInteger('repository_import_id');$t->unsignedBigInteger('curriculum_source_id')->nullable();$t->string('relative_path')->nullable();$t->string('status',30);$t->string('message')->nullable();$t->json('inferred_metadata')->nullable();$t->timestamps();$t->index(['repository_import_id','status']);});
Schema::create('lesson_plan_sources',function(Blueprint $t){$t->id();$t->unsignedBigInteger('lesson_plan_id');$t->unsignedBigInteger('curriculum_source_id');$t->unsignedBigInteger('curriculum_fragment_id')->nullable();$t->decimal('relevance_score',7,4)->nullable();$t->unsignedSmallInteger('rank')->nullable();$t->string('generation_type',30);$t->timestamps();$t->index(['lesson_plan_id','generation_type']);});}
public function down():void{Schema::dropIfExists('lesson_plan_sources');Schema::dropIfExists('repository_import_items');Schema::dropIfExists('repository_imports');Schema::dropIfExists('curriculum_topics');Schema::table('curriculum_sources',fn(Blueprint $t)=>$t->dropColumn(['source_class_level_id','curriculum_level_id','term_id','week_number','original_filename','mime_type','file_size','raw_text','cleaned_text','extraction_status','index_status','needs_review','archived_at']));Schema::table('lesson_plans',fn(Blueprint $t)=>$t->dropColumn(['curriculum_level_id','delivery_type','published_at']));}};
